---
- name: PostgreSQL installation (PG Debian)
  apt:
    name: "postgresql-{{ pg.ver }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  notify:
    - restart pg
- name: PostgreSQL listen_address configuration (PG Debian)
  lineinfile:
    path: "/etc/postgresql/{{ pg.ver }}/main/postgresql.conf"
    line: "listen_addresses = '*'" 
    insertafter: "^#listen_addresses" 
    backup: true
  notify:
    - restart pg
- name: Change pg_hba.conf (PG Debian)
  postgresql_pg_hba:
    dest: "/etc/postgresql/{{ pg.ver }}/main/pg_hba.conf"
    contype: host
    users: "all"
    source: "0.0.0.0/0"
    databases: "all"
    method: md5
    create: true
  notify:
    - restart pg
- name: Tune parameters (PG Debian)
  blockinfile:
    block: "{{ pg.conf }}"
    path: "/etc/postgresql/{{ pg.ver }}/main/conf.d/custom.conf"
    create: yes
  notify:
    - restart pg
- name: NFS installation (PG Debian)
  apt:
    name: ['nfs-common']
    state: present
    update_cache: yes
    force_apt_get: yes
  when: fs.type == "nfs"
- name: Create role (PG)
  postgresql_user:
    db: postgres
    name: "{{ pg.user }}"
    priv: "CONNECT"
    expires: infinity
    role_attr_flags: CREATEDB,CREATEROLE
  become: yes
  become_user: postgres
- name: Save query into variable (PG Debian)
  set_fact:
    create_query: "{{ lookup('file', 'files/sql/pg.sql') }}"
- name: Create table (PG Debian)
  postgresql_query: 
    db: postgres
    query: "{{ create_query }}"
  become: yes
  become_user: postgres
- name: Change privileges in public (PG Debian)
  postgresql_privs:
    db: postgres
    schema: public
    privs: ALL
    type: table
    objs: mgmt_task 
    role: "{{ pg.user }}"
  become: yes
  become_user: postgres
