---
- name: PostgreSQL installation (PG Debian)
  apt:
    name: "postgresql-{{ pg.ver }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  notify:
    - restart pg
- name: PostgreSQL listen_address configuration (PG Debian)
  lineinfile:
    path: "/etc/postgresql/{{ pg.ver }}/main/postgresql.conf"
    line: "listen_addresses = '*'" 
    insertafter: "^#listen_addresses" 
    backup: true
  notify:
    - restart pg
- name: Copy files (PG)
  template:
    src: "pg_hba.conf.j2"
    dest: "/etc/postgresql/12/main/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    backup: yes
    mode: '0640'
  notify:
    - restart pg
- name: NFS installation (PG Debian)
  apt:
    name: ['nfs-common']
    state: present
    update_cache: yes
    force_apt_get: yes
  when: fs.type == "nfs"
- name: Create role (PG)
  postgresql_user:
    db: postgres
    name: "{{ pg.user }}"
    priv: "CONNECT"
    expires: infinity
    role_attr_flags: CREATEDB,CREATEROLE
  become: yes
  become_user: postgres
