- name: Add the user for worker (PG, MySQL)
  user:
    name: "{{ os.user }}"
    uid: "{{ os.uid }}"
    shell: /bin/bash
- include_tasks: "{{ ansible_distribution }}_common.yml"
- include_tasks: "{{ ansible_distribution }}_pg.yml"
  when: type == "pg" 
- include_tasks: "{{ ansible_distribution }}_mysql.yml"
  when: type == "mysql" 
- include_tasks: "srv.yml"
  when: ansible_host != mgmt_host
- include_tasks: "{{ ansible_distribution }}_mgmt.yml"
  when: ansible_host == mgmt_host
- include_tasks: "mgmt.yml"
  when: ansible_host == mgmt_host
- include_tasks: "additions.yml" 
- include_tasks: "share.yml" 
