---
- name: Copy files (PG MySQL)
  copy:
    src: "{{ type }}_worker/{{ item }}"
    dest: "~{{ os.user }}/{{ item }}"
    owner: "{{ os.user }}"
    mode: '0750'
  with_items:
    - local_worker_async.py
    - local_worker.py
    - remote_worker.py
- name: Copy files (PG MySQL)
  template:
    src: "{{ type }}_worker/{{ item }}.j2"
    dest: "~{{ os.user }}/{{ item }}"
    owner: "{{ os.user }}"
    mode: '0750'
  with_items:
    - worker.env
- name: Create Systemd units
  copy:
    src: "{{ type }}_worker/{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
    owner: "root"
    mode: '640'
  with_items:
    - local-worker-async.service
    - local-worker.service
    - remote-worker.service
- name: Systemd reread configs
  systemd:
    daemon_reload: yes
  notify:
    - start remote-worker  
    - start local-worker
    - start local-async-worker
