all:
  children:
    db:
      children:
        pg:
          hosts:
            pg1:
            pg2:
          vars:
            type: pg
            ansible_python_interpreter: /usr/bin/python3
        mysql:
          hosts:
            mysql1:
            mysql2:
          vars:
            type: mysql
            ansible_python_interpreter: /usr/bin/python3
        pgm:
          hosts:
            pg-mgmt:
          vars:
            type: mgmt
            ansible_python_interpreter: /usr/bin/python3
